# Generated by Django 4.1.7 on 2023-04-02 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idpay',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('transId', models.CharField(max_length=50, unique=True)),
                ('lastStatus', models.IntegerField(blank=True, null=True)),
                ('trackIdpay', models.IntegerField(blank=True, null=True)),
                ('trackShaparak', models.CharField(blank=True, max_length=50, null=True)),
                ('amountCreate', models.IntegerField(blank=True, null=True)),
                ('amountPaid', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('dateShaparak', models.DateTimeField(blank=True, null=True)),
                ('dateVerify', models.DateTimeField(blank=True, null=True)),
                ('cardNo', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
